
- hosts: all
  tasks:
  - name: install apache on ubuntu
    apt:
      name: apache2
      state: latest
      update_cache: true
    become: yes
    when: ansible_os_family == "Debian"
  - name: install apache on centos
    yum:
      name: httpd
      state: latest
    become: yes
    when: ansible_os_family == "RedHat"
  - name: Install IIS on windows
    win_feature:
      name: Web-Server
      state: present
    when: ansible_os_family == "Windows"
  - name: start apache service on ubuntu
    service:
      name: apache2
      state: started
      enabled: true
    become: yes
    when: ansible_os_family == "Debian"
  - name: start apache service on centos
    service:
      name: httpd
      state: started
      enabled: true
    become: yes
    when: ansible_os_family == "RedHat"
  - name: Start IIS on windows
    win_service:
      name: W3SVC
      state: started
      start_mode: auto
    when: ansible_os_family == "Windows"
  - name: Copy Index.html file to ubuntu node
    template:
      src: /etc/ansible/playbooks/index.html.j2
      dest: /var/www/html/index.html
    become: yes
    notify: restart apache2
    when: ansible_os_family == "Debian"
  - name: Copy Index.html file to centos node
    template:
      src: /etc/ansible/playbooks/index.html.j2
      dest: /var/www/html/index.html
    become: yes
    notify: restart httpd
    when: ansible_os_family == "RedHat"
  - name: Copy Index.html to windows node
    template:
      src: /etc/ansible/playbooks/index.html.j2
      dest: C:\inetpub\wwwroot\index.html
    notify: restart iis
    when: ansible_os_family == "Windows"

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
      become: yes
    - name: restart httpd
      service:
        name: httpd
        state: restarted
      become: yes
    - name: restart iis
      win_service:
        name: W3SVC
        state: restarted
