---
- name: install apache on ubuntu
  apt:
    name: apache2
    state: latest
    update_cache: true
  become: yes
  when: ansible_os_family == "Debian"
- name: install apache on centos
  yum:
    name: httpd
    state: latest
  become: yes
  when: ansible_os_family == "RedHat"
- name: Install IIS on windows
  win_feature:
    name: Web-Server
    state: present
  when: ansible_os_family == "Windows"
